#!/usr/bin/python

import pprint
import json
import yaml
from pathlib import Path

for f in Path(Path(__file__).parent).glob('*.yaml'):
    with open(f, 'r') as fh:
        data = yaml.safe_load(fh)

    fj = f.as_posix().replace('yaml', 'json')
    with open(fj, 'w') as fh:
        json.dump(data, fh, indent=2)

#with open("spruance.json", 'r') as fh:
#    data = json.load(fh)

#with open('spruance.yaml', 'w') as f:
#    yaml.dump(data, f)

#with open('spruance.json', 'w') as f:
#    json.dump(data, f, sort_keys = False, indent = 2)

#pprint.PrettyPrinter().pprint(data)

